---
apiVersion: v1
kind: Service
metadata:
  name: petclinic-svc
spec:
  type: ClusterIP
  selector:
    app: petclinic-app
  ports:
    - name: petsvcport
      port: 8080
      targetPort: petwebport
      protocol: TCP