---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-deploy
spec:
  minReadySeconds: 2
  replicas: 1
  selector:
    matchLabels:
      app: petclinic-pod
  template:
    metadata:
      name: petclinic-pod
      labels:
        app: petclinic-app
    spec:
      imagePullSecrets:
        name: regcred
      containers:
        - name: petclinic-container
          image: sourcetrace.jfrog.io/workshop-docker/petclinic:latest
          ports:
            - name: petwebport
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi              
          livenessProbe:
            httpGet:
              path: /
              port: petwebport
            failureThreshold: 3
            periodSeconds: 3
            successThreshold: 1
            initialDelaySeconds: 90
          readinessProbe:
            httpGet:
              path: /
              port: petwebport
            failureThreshold: 3
            periodSeconds: 3
            successThreshold: 1
            initialDelaySeconds: 90
